name: D8 build

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *' # Run every day

permissions:
  pull-requests: write
  contents: write

jobs:
  upgrade:
    name: Upgrade V8
    runs-on: ubuntu-22.04
    outputs:
      v8_version: ${{ steps.check_version.outputs.NEW_V8_VERSION }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: false
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      - name: Run upgrade script
        id: check_version
        working-directory: ./deps
        run: ./v8_upgrade.sh

  build:
    name: Build V8 for ${{ matrix.platform }} ${{ matrix.arch }}
    runs-on: ${{ matrix.platform }}
    needs: upgrade
    if: needs.upgrade.outputs.v8_version != '0'
    strategy:
      fail-fast: true
      matrix:
        platform: [ubuntu-22.04, macos-latest]
        #platform: [ macos-latest]
        arch: [x64]
        #arch: [x64, arm64]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
          clean: true
          fetch-depth: 1

      - name: Update version file
        shell: bash
        run: echo -n "${{ needs.upgrade.outputs.v8_version }}" > deps/VERSION

      - name: Build Release for Linux
        if: startsWith(matrix.platform, 'ubuntu')
        uses: ./.github/actions/build-linux
        with:
          target-arch: ${{ matrix.arch }}

      - name: Build Release for macOS
        if: startsWith(matrix.platform, 'macos')
        uses: ./.github/actions/build-macos
        with:
          target-arch: ${{ matrix.arch }}

      - name: Set v8 build name
        working-directory: ./deps
        shell: bash
        run: |
          target_arch="$1"
          os=$(echo "$(uname -s)" | tr '[:upper:]' '[:lower:]')
          archive_name="v8_${os}_${{ matrix.arch }}"
          echo "Using Archive Name: $archive_name"
          echo "ARCHIVE_NAME=$archive_name" >> "$GITHUB_ENV"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARCHIVE_NAME }}
          path: deps/v8/out/release/d8
          retention-days: 1
